### ISSUE TITLE
Error downloading file leads to crash

### ISSUE THREAD

**Issue by Popolechien** [offspot/kiwix-hotspot#622]
These two jobs https://cardshop.hotspot.kiwix.org/all-orders/617a98e898c8bf573d4a8c5b and https://cardshop.hotspot.kiwix.org/all-orders/6170e3c098c8bf56054a8f33 both failed after not being able to retrieve a file from the mirror(s). 

Could there be a way to 1) skip the file, move on and try again when the rest of the queue is downloaded or 2) try another mirror?

**Comment by kelson42** [comment]
@rgaudin Do we have anything to fix or improve here? If a zim file is not available for any reason, a handled stop seems to be the appropriate behaviour to me.

**Comment by rgaudin** [comment]
That is the current behavior, @Popolechien use the word "crash" because the cardshop order fails but it's just the installer halting itself after a non-zero return code from aria2

**Comment by kelson42** [comment]
@rgaudin Does this ticket should lead to a better/clearer error mgmt at cardshop level in the case of such a scenario?

**Comment by rgaudin** [comment]
No. reread the ticket. @Popolechien wants the installer to skip failed-downloads, continue with other stuf and te-retry those. It's unrealistic

**Comment by Popolechien** [comment]
Well I certainly could live with a better error message than `failed`. Like, if the issue fails because a file is missing/corrupted or whatever, the user might want to simply know which one so as to be able to decide if they want to relaunch immediately an order without said file rather than wait for an hypothetical fix.
I'll open a ticket to that effect if it makes sense to you.

**Comment by kelson42** [comment]
@Popolechien makes sense to me at least.

**Comment by rgaudin** [comment]
@Popolechien you've been advocating for us to provide the least possible amount of information to users. This goes the other way around but I think I understand the reasoning: that information will be actionable (change config and relaunch).

While I'm OK with a better error message in the cardshop, I'm strongly against *normalizing* some errors which would only lead to distrust in the solution. A download error is a major problem that usually roots to:

- a network issue we can't do much about. For aria2 to fail, it means it was longer than just a blink (there are retry mechanisms)
- a network/configuration issue. We need to be informed about this as this won't get fixed by itself.
- a missing file: library out of sync or deleted file. Idem, that's something we need to fix.

Without an actual incident, and a ticket, problems will add-up.

The download reason can be found in the logs. We surely can improve the reporting on the cardshop so that @Popolechien can easily know what went wrong ; maybe to communicate more with the client and/or the devs.

But telling users that should a download fail (ie. it fails frequently), one can edit its config and restart without that ZIM is terrible image IMO.

Also, it's probably wrong because I think single-zim issues are very rare and additionaly, I don't think download issues are that frequent. Or those are not reported…

**Comment by Popolechien** [comment]
Ok I get your point, will not push it further for the time being.

**Comment by rgaudin** [comment]
We'll make sure we have proper/clean error reporting in 3.0 as the installer will thus mostly be download + extraction and not this super-long qemu black box
