### ISSUE TITLE
Hotspot Installer Content Catalog Fail

### ISSUE THREAD

**Issue by kelson42** [offspot/kiwix-hotspot#677]
From kiwix-desktop created by [mikejfeser](https://github.com/mikejfeser): kiwix/kiwix-desktop#941  

![image](https://user-images.githubusercontent.com/60615050/236714858-01a80b1c-9c9a-4035-a143-59308e0efe46.png)
![image](https://user-images.githubusercontent.com/60615050/236714898-48e0498a-0759-4232-af2e-506e67c27e4e.png)

Hello,

When running the hotspot installer, I am unable to load static content. It warns that I should check internet/proxy settings, however, when going to proxy settings and test connection, I can confirm that I can reach the Kiwix servers. Any assistance would be much appreciated!

**Comment by kelson42** [comment]
This is a ticket for https://github.com/offspot/kiwix-hotspot, I will move it.

**Comment by rgaudin** [comment]
I can't reproduce on Win11. Which version of Windows are you running?
Can you access `http://mirror.download.kiwix.org/library/ideascube.yml` from your web browser?

**Comment by mikejfeser** [comment]
Windows 10, and yes I can access that address.

**Comment by rgaudin** [comment]
I'm sorry I can't reproduce the issue.

<img width="1271" alt="Screenshot 2023-06-06 at 10 46 26" src="https://github.com/offspot/kiwix-hotspot/assets/57929/3204b1ab-09ba-43cf-a9af-4e00395e7b31">

It shouldn't make a difference but I'd advise you to try the 2.4.11 as 2.4.12 has an important bug on Windows that would affect you anyway.

**Comment by LuxStatera** [comment]
Same issue on Linux and Mac

**Comment by LuxStatera** [comment]
I just tried this link "http://mirror.download.kiwix.org/library/ideascube.yml" and it works. It opens a page with a bunch of text. I'm in the US

**Comment by rgaudin** [comment]
I'll look into it. Are you using a Mac? You seem to have tested on various platforms but I'll try to reproduce on yours

**Comment by LuxStatera** [comment]
I am using a Mac but I also tried Linux. Both failed. Also I can't find the Windows version so I wasn't able to test on Windows. The Kiwix website only shows a Mac and Linux installer

**Comment by LuxStatera** [comment]
@rgaudin Also do you have a link to the Windows installer? I haven't tried that one yet because I couldn't find it

**Comment by LuxStatera** [comment]
@rgaudin Thank you. I tried version 2.4.11 and 2.4.13 on Windows 10 but I am still getting the same error

**Comment by LuxStatera** [comment]
@rgaudin How did the testing go?

**Comment by rgaudin** [comment]
Sorry I could not find time yet to look at this. Thanks for the reminder.

**Comment by LuxStatera** [comment]
Not stale. 

@rgaudin what's the word?

**Comment by rgaudin** [comment]
Sorry I'm running out of ideas. Couple things to try:

- Running the GUI from the Console so we get a chance to see if there's additional debug info. There might be a line like `Exception while downloading/parsing catalogs` with details. To do this, you must unpack the windows exe file with 7zip then launch it from the console/terminal. On macOS it's simple as `/Applications/Kiwix\ Hotspot.app/Contents/MacOS/kiwix-hotspot` from the terminal. Beware launching from terminal doesn't focus the App Window. Find it in dock to reveal it.
- Running the CLI version. It's not embedded in Windows version I think so that would be macOS or Linux. The most reliable version, anyway, is Linux version with `--root` flag.

The CLI version can be used with a JSON Config file created with the GUI. That's handy so you don't have to use CLI to select content which is hardly for human… but for that you'd need the GUI to be able to access the catalog.

```sh
kiwix-hotspot cli --root --config myconfig.json --size 16G
```

**Comment by kelson42** [comment]
Unfortunately this product has been discontinued. Therefore this issue won't be fixed/implemented. A bit more details can be found [here](https://github.com/offspot/kiwix-hotspot/blob/main/README.md).
