### ISSUE TITLE
Unable to pick-up network

### ISSUE THREAD

**Issue by Popolechien** [offspot/kiwix-hotspot#691]
I created a 350 Gb configuration using the latest version of the imager, which I flashed without issue onto a brand new microSD ard ([SanDisk Extreme microSDXC U3 card A2 (2022) - 512GB](https://www.prodimex.ch/136474)).

I put the card in a Raspberry 3B and 4 and in neither case could I see a network appear (3 different android phones + 1 macOS), even after several minutes.

Config is at https://imager.kiwix.org/configurations/1004

**Comment by rgaudin** [comment]
Thanks for the report. Please keep creating draft issues on the [project](https://github.com/orgs/offspot/projects/2) for imager-related issues.

As you can see on [your order](https://imager.kiwix.org/all-orders/65a559e1c056cd14fe6ff2fd)'s (correct) config details:

```json
{
    ...
    "name": "Test large image",
    "project_name": "kiwix",
    "size": "512 GB",
}
```

This got turned into the following due to issue https://github.com/offspot/cardshop/issues/355

```yaml
  ap:
    domain: Test large image
    tld: hotspot
    ssid: Test large image
```

That issue was fixed before you created your order but it wasn't deployed at that time, hence your issue.
It's only the following day that https://github.com/offspot/cardshop/issues/359 was setup.
